--- qiskit-ignis/qiskit-ignis#240/after/qiskit>ignis>verification>randomized_benchmarking>fitters.py	2022-01-10 16:02:54.000000000 +0000
+++ qiskit-ignis/qiskit-ignis#240/before/qiskit>ignis>verification>randomized_benchmarking>fitters.py	2022-01-10 16:02:54.000000000 +0000
@@ -238,6 +238,12 @@
                 if nseeds_circ not in self._nseeds:
                     self._nseeds.append(nseeds_circ)
 
+        for result in self._result_list:
+            if not len(result.results) == len(self._cliff_lengths[0]):
+                raise ValueError(
+                    "The number of clifford lengths must match the number of "
+                    "results")
+
         if rerun_fit:
             self.calc_data()
             self.calc_statistics()
@@ -516,9 +522,7 @@
 
         self.rbfit_std.add_data(original_result)
         self.rbfit_int.add_data(interleaved_result)
-
-        if not (original_result is None and interleaved_result is None):
-            self.fit_data()
+        self.fit_data()
 
     @property
     def rbfit_std(self):
@@ -909,10 +913,6 @@
             the output of circuits generated by randomized_becnhmarking_seq
             where is_purity = True.
         """
-
-        if new_purity_result is None:
-            return
-
         self.rbfit_pur.add_data(new_purity_result, rerun_fit)
 
         if rerun_fit:
